name: Security Audit

on:
  schedule:
    - cron: "0 2 * * 1" # Runs every Monday at 2 AM
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Run npm audit
      run: npm audit